#!/bin/bash
#------------------------------------------------------------------------------
# Copyright (C) 2021 Kalycito Infotech Private Limited
# Author: Kalycito Infotech Private Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------

touch /usr/local/src/cpu_utility.txt

while :
do
  cpu_utilization=$(mpstat -P ALL 1 300 | \
                    awk '/Average:/' | \
                    tail -n +3 | \
                    awk '{print $3,$4,$5,$6,$7,$8,$9,$10,$11}');
  echo "$cpu_utilization" > /usr/local/src/cpu_utility.txt;
done
