#!/bin/bash
#------------------------------------------------------------------------------
# Copyright (C) 2021 Kalycito Infotech Private Limited
# Author: Kalycito Infotech Private Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------

###############################################################################
# Global Variable - constant                                                  #
###############################################################################
INTERFACE=${0##*/ethtool_rx_queue_statistics_compute_}

if [ -s "$file" ]; then
    received_packet_queue_1_before=`cat $file | tr -s " " | cut -d" " -f2`
    received_packet_queue_1_now=`sudo ethtool -S $INTERFACE | grep rx_queue_1_packets | cut -d ':' -f2`
    received_packet_queue_1_previouscycle=`cat $file | tr -s " " | cut -d" " -f1`
    if test $received_packet_queue_1_previouscycle -eq $received_packet_queue_1_now
    then
        received_packet_queue_1="$(($received_packet_queue_1_now-$received_packet_queue_1_previouscycle))"
    else
        received_packet_queue_1="$(($received_packet_queue_1_now-$received_packet_queue_1_before))"
    fi
    dropped_packet_queue_1_before=`cat $file | tr -s " " | cut -d" " -f4`
    dropped_packet_queue_1_now=`sudo ethtool -S $INTERFACE | grep rx_queue_1_drops | cut -d ':' -f2`
    dropped_packet_queue_1_previouscycle=`cat $file | tr -s " " | cut -d" " -f3`
    if test $dropped_packet_queue_1_previouscycle -eq $dropped_packet_queue_1_now
    then
        dropped_packet_queue_1="$(($dropped_packet_queue_1_now-$dropped_packet_queue_1_previouscycle))"
    else
        dropped_packet_queue_1="$(($dropped_packet_queue_1_now-$dropped_packet_queue_1_before))"
    fi
    sudo bash -c "echo $received_packet_queue_1_now $received_packet_queue_1 $dropped_packet_queue_1_now $dropped_packet_queue_1 > $file"
fi



