#!/bin/bash
#------------------------------------------------------------------------------
# Copyright (C) 2021 Kalycito Infotech Private Limited
# Author: Kalycito Infotech Private Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------

###############################################################################
# Global Variable - constant                                                  #
###############################################################################
INTERFACE=${0##*/ethtool_rx_queue_statistics_compute_}

file=/usr/local/src/ethtool_receive_statistics_"$INTERFACE".txt

if test -s "$file" ; then
    received_packet_queue_2_before=`cat $file | \
                                    tr -s " " | \
                                    cut -d" " -f1`
    received_packet_queue_2_now=`sudo ethtool -S "$INTERFACE" | \
                                 grep rx_queue_2_packets | \
                                 cut -d ':' -f2`
    received_packet_queue_2=\
"$(($received_packet_queue_2_now-$received_packet_queue_2_before))"
    dropped_packet_queue_2_before=`cat $file | \
                                   tr -s " " | \
                                   cut -d" " -f2`
    dropped_packet_queue_2_now=`sudo ethtool -S "$INTERFACE" | \
                                grep rx_queue_2_drops | \
                                cut -d ':' -f2`
    dropped_packet_queue_2=\
"$(($dropped_packet_queue_2_now-$dropped_packet_queue_2_before))"
    sudo bash -c "echo $received_packet_queue_2 $dropped_packet_queue_2 > \
                  $file"
fi



