#!/bin/sh
#------------------------------------------------------------------------------
# Copyright (C) 2021 Kalycito Infotech Private Limited
# Author: Kalycito Infotech Private Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------

###############################################################################
# Global Variable - constant                                                  #
###############################################################################
INTERFACE=${0##*/network_bandwidth_utilisation_compute_}
STATISTIC_FILE=/usr/local/src/network_bandwidth_utilisation

#Measure the network bandwidth of the various interfaces present in the Node
ifstat -i $INTERFACE,${INTERFACE}.1,${INTERFACE}.2,${INTERFACE}.3,\
    ${INTERFACE}.4,${INTERFACE}.5,${INTERFACE}.6,${INTERFACE}.7,\
    ${INTERFACE}.8 1 1 > ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt

if test -e ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt; then
    sed -i '/enp2s0/d' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt
    sed -i '/KB/d' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt
    sed -i 's/^[[:space:]]*//g' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt
fi

awk '{print $1" "$2}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.txt

awk '{print $3" "$4}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.1.txt

awk '{print $5" "$6}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.2.txt

awk '{print $7" "$8}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.3.txt

awk '{print $9" "$10}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.4.txt

awk '{print $11" "$12}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.5.txt

awk '{print $13" "$14}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.6.txt

awk '{print $15" "$16}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.7.txt

awk '{print $17" "$18}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.8.txt







