#!/bin/sh
#------------------------------------------------------------------------------
# Copyright (C) 2021 Kalycito Infotech Private Limited
# Author: Kalycito Infotech Private Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# -----------------------------------------------------------------------------

###############################################################################
# Global Variable - constant                                                  #
###############################################################################
INTERFACE=${0##*/network_bandwidth_utilisation_compute_}
STATISTIC_FILE=/usr/local/src/network_bandwidth_utilisation

HISTDIR=/sys/class/net/$INTERFACE/statistics
if test -e $HISTDIR
then
    tx_bytes=`cat /usr/local/src/network_bandwidth_utilisation_$INTERFACE.txt | cut -d" " -f1`
    rx_bytes=`cat /usr/local/src/network_bandwidth_utilisation_$INTERFACE.txt | cut -d" " -f2`
    tx_bytes_now=`cat $HISTDIR/tx_bytes`; rx_bytes_now=`cat $HISTDIR/rx_bytes`
    outgoing_bandwidth="$((($tx_bytes_now-$tx_bytes) / 300))"
    incoming_bandwidth="$((($rx_bytes_now-$rx_bytes) / 300))"
    sudo bash -c "echo $tx_bytes_now $rx_bytes_now $outgoing_bandwidth $incoming_bandwidth > /usr/local/src/network_bandwidth_utilisation_$INTERFACE.txt"
fi

for j in `seq 1 8`; do
    HISTDIR=/sys/class/net/$INTERFACE.$j/statistics
    if test -e $HISTDIR
    then
        tx_bytes=`cat /usr/local/src/network_bandwidth_utilisation_$INTERFACE.$j.txt | cut -d" " -f1`
        rx_bytes=`cat /usr/local/src/network_bandwidth_utilisation_$INTERFACE.$j.txt | cut -d" " -f2`
        tx_bytes_now=`cat $HISTDIR/tx_bytes`; rx_bytes_now=`cat $HISTDIR/rx_bytes`
        outgoing_bandwidth="$((($tx_bytes_now-$tx_bytes) / 300))"
        incoming_bandwidth="$((($rx_bytes_now-$rx_bytes) / 300))"
        sudo bash -c "echo $tx_bytes_now $rx_bytes_now $outgoing_bandwidth $incoming_bandwidth > /usr/local/src/network_bandwidth_utilisation_$INTERFACE.$j.txt"
    fi
done

awk '{print $1" "$2}' ${STATISTIC_FILE}_${INTERFACE}_and_VLAN.txt > \
    ${STATISTIC_FILE}_${INTERFACE}.txt






