#define EF_TOK_AND                              1
#define EF_TOK_OR                               2
#define EF_TOK_UNARY_OP                         3
#define EF_TOK_BINARY_OP                        4
#define EF_TOK_BETWEEN                          5
#define EF_TOK_INLIST                           6
#define EF_TOK_SELECT                           7
#define EF_TOK_COMMA                            8
#define EF_TOK_WHERE                            9
#define EF_TOK_LPAREN                          10
#define EF_TOK_RPAREN                          11
#define EF_TOK_LITERAL                         12
#define EF_TOK_SAO                             13
#define EF_TOK_NAMEDOPERAND                    14
#define EF_TOK_LBRACKET                        15
#define EF_TOK_RBRACKET                        16
#define EF_TOK_FOR                             17
#define EF_TOK_COLONEQUAL                      18
