/* A recursive-descent parser generated by peg 0.1.18 */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 *    Copyright 2023-2024 (c) Fraunhofer IOSB (Author: Florian Düwel)
 *    Copyright 2024 (c) Fraunhofer IOSB (Author: Julius Pfrommer)
 */

#include <open62541/util.h>
#include "ua_eventfilter_parser.h"

/*
 *  Lexing and parsing of OPC UA eventfilter. These are helper functions that
 *  are not required by the SDk internally. But they are useful for users who want to create
 *  eventfilter from human readable strings.
 *
 *  This compilation unit uses the leg parser generators (https://www.piumarta.com/software/peg/peg.1.html).
 *  The final C source is generated with the following script:
 *
 *  leg -Po ua_eventfilter_grammar.c ua_eventfilter_grammar.leg
 *
 *  However, the generated eventfilter_parser_grammar.c file creates some compiler warnings.
 *  Here is an Explanation on how to remove these warnings:
 *  windows build:
 *
 *   1 #define YY_INPUT(yyctx, buf, result, max_size) \
 *   2 {                                              \
 *   3  if(yyctx->input.length <= yyctx->pos) {      \
 *   4      result = 0;                              \
 *   5  } else {                                     \
 *   6      result = ((int) yyctx->input.length) - yyctx->pos;\
 *   7      if(result > max_size)                     \
 *   8          result = max_size;                   \
 *   9      memcpy(buf, &yyctx->input.data[yyctx->pos], result); \
 *   10      yyctx->pos += result;                    \
 *   11  }                                            \
 *   12}
 *   replace: yyctx->input.length with  ((int) yyctx->input.length) in line 6
 *
 *   13 YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
 *   14 {
 *   15   yy->__val += count;
 *   16   while (yy->__valslen <= yy->__val - yy->__vals)
 *   17     {
 *   18       long offset= (long)( yy->__val - yy->__vals);
 *   19       yy->__valslen *= 2;
 *   20       yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
 *   21       yy->__val= yy->__vals + offset;
 *   22     }
 *   23 }
 *   replace: long offset= yy->__val - yy->__vals; with long offset= (long)( yy->__val - yy->__vals); in line 18
 *
 *   linux build:
 *
 *   replace YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart) with YY_PARSE(static int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
 *   replace YY_PARSE(int) YYPARSE(YY_CTX_PARAM) with YY_PARSE(static int) YYPARSE(YY_CTX_PARAM)
 *   replace YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx) with YY_PARSE(static yycontext *) YYRELEASE(yycontext *yyctx)
 *
 *   remove:
 *   YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
 *   {
 *     if (tp0)
 *       {
 *         fprintf(stderr, "accept denied at %d\n", tp0);
 *         return 0;
 *       }
 *     else
 *       {
 *         yyDone(yy);
 *         yyCommit(yy);
 *       }
 *     return 1;
 *   }
 *
 *  In order that users of the SDK don't need to use the leg parser, always commit a recent
 *  eventfilter_parser_grammar.c if changes are made to the lexer.
 */

#define YY_CTX_LOCAL 1
#define YY_CTX_MEMBERS                  \
    UA_StatusCode status;               \
    UA_String input;                    \
    UA_UInt32 pos;                      \
    OperandList global;                 \
    Operand *top;

#define YY_INPUT(yyctx, buf, result, max_size) \
{                                              \
  if(yyctx->input.length <= yyctx->pos)  {      \
      result = 0;                              \
  } else {                                     \
      result = (int)(yyctx->input.length - yyctx->pos); \
      if(result > max_size)                     \
          result = max_size;                   \
      memcpy(buf, &yyctx->input.data[yyctx->pos], result); \
      yyctx->pos += result;                    \
  }                                            \
}

#define YYSTYPE Operand *


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= (long)(yy->__val - yy->__vals);
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_Comment(yycontext *yy); /* 32 */
YY_RULE(int) yy_Enter(yycontext *yy); /* 31 */
YY_RULE(int) yy_Space(yycontext *yy); /* 30 */
YY_RULE(int) yy_JsonValue(yycontext *yy); /* 29 */
YY_RULE(int) yy_JsonArray(yycontext *yy); /* 28 */
YY_RULE(int) yy_JsonElement(yycontext *yy); /* 27 */
YY_RULE(int) yy_EscapedString(yycontext *yy); /* 26 */
YY_RULE(int) yy_Ref(yycontext *yy); /* 25 */
YY_RULE(int) yy_JsonObject(yycontext *yy); /* 24 */
YY_RULE(int) yy_QualifiedName(yycontext *yy); /* 23 */
YY_RULE(int) yy_QuotedString(yycontext *yy); /* 22 */
YY_RULE(int) yy_NumericRange(yycontext *yy); /* 21 */
YY_RULE(int) yy_Attribute(yycontext *yy); /* 20 */
YY_RULE(int) yy_Path(yycontext *yy); /* 19 */
YY_RULE(int) yy_NodeId(yycontext *yy); /* 18 */
YY_RULE(int) yy_BinaryFilter(yycontext *yy); /* 17 */
YY_RULE(int) yy_UnaryFilter(yycontext *yy); /* 16 */
YY_RULE(int) yy_InListOperator(yycontext *yy); /* 15 */
YY_RULE(int) yy_BetweenOperator(yycontext *yy); /* 14 */
YY_RULE(int) yy_BinaryOperator(yycontext *yy); /* 13 */
YY_RULE(int) yy_UnaryOperator(yycontext *yy); /* 12 */
YY_RULE(int) yy_SimpleAttributeOperand(yycontext *yy); /* 11 */
YY_RULE(int) yy_Literal(yycontext *yy); /* 10 */
YY_RULE(int) yy_RefAssignment(yycontext *yy); /* 9 */
YY_RULE(int) yy_RefOperand(yycontext *yy); /* 8 */
YY_RULE(int) yy_Operator(yycontext *yy); /* 7 */
YY_RULE(int) yy_Operand(yycontext *yy); /* 6 */
YY_RULE(int) yy_ForClause(yycontext *yy); /* 5 */
YY_RULE(int) yy_WhereClause(yycontext *yy); /* 4 */
YY_RULE(int) yy_SelectClause(yycontext *yy); /* 3 */
YY_RULE(int) yy__(yycontext *yy); /* 2 */
YY_RULE(int) yy_EventFilter(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_RefAssignment(yycontext *yy, char *yytext, int yyleng)
{
#define op yy->__val[-1]
#define r yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_RefAssignment\n"));
  {
  op->ref = save_string(r->operand.ref);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op
#undef r
}
YY_ACTION(void) yy_1_RefOperand(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_RefOperand\n"));
  {
  __ = create_operand(&yy->global, OT_REF); __->operand.ref = save_string(yytext);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_24_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_24_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_BOOLEAN]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_23_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_23_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_INT32]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_22_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_22_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_STRING]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_21_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_21_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_VARIANT]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_20_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_20_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_LOCALIZEDTEXT]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_19_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_19_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_QUALIFIEDNAME]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_18_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_18_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_EXPANDEDNODEID]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_17_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_17_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_STATUSCODE]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_16_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_16_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_BYTESTRING]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_15_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_15_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_GUID]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_14_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_14_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_DATETIME]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_13_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_13_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_BYTE]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_12_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_12_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_SBYTE]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_11_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_11_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_NODEID]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_10_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_FLOAT]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_9_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_DOUBLE]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_UINT64]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_UINT32]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_UINT16]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_INT64]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_INT16]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_BOOLEAN]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_STRING]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Literal(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Literal\n"));
  {
  __ = parse_literal(&yy->global, yytext, &UA_TYPES[UA_TYPES_INT32]);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_SimpleAttributeOperand(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SimpleAttributeOperand\n"));
  {
  __ = create_operand(&yy->global, OT_SAO);
     yy->status |= UA_SimpleAttributeOperand_parse(&__->operand.sao, UA_STRING(yytext));
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_InListOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op3 yy->__val[-1]
#define op2 yy->__val[-2]
#define op1 yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_InListOperator\n"));
  {
  append_operand(&__->operand.op, op3);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op3
#undef op2
#undef op1
}
YY_ACTION(void) yy_3_InListOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op3 yy->__val[-1]
#define op2 yy->__val[-2]
#define op1 yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_InListOperator\n"));
  {
  append_operand(&__->operand.op, op2);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op3
#undef op2
#undef op1
}
YY_ACTION(void) yy_2_InListOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op3 yy->__val[-1]
#define op2 yy->__val[-2]
#define op1 yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_InListOperator\n"));
  {
  append_operand(&__->operand.op, op1);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op3
#undef op2
#undef op1
}
YY_ACTION(void) yy_1_InListOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op3 yy->__val[-1]
#define op2 yy->__val[-2]
#define op1 yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_InListOperator\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_INLIST);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op3
#undef op2
#undef op1
}
YY_ACTION(void) yy_1_BetweenOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op3 yy->__val[-1]
#define op2 yy->__val[-2]
#define op1 yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_BetweenOperator\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_BETWEEN); append_operand(&__->operand.op, op1);
     append_operand(&__->operand.op, op2); append_operand(&__->operand.op, op3);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op3
#undef op2
#undef op1
}
YY_ACTION(void) yy_1_BinaryOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op2 yy->__val[-1]
#define op1 yy->__val[-2]
#define filter yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_BinaryOperator\n"));
  {
  __ = filter; append_operand(&__->operand.op, op1); append_operand(&__->operand.op, op1);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op2
#undef op1
#undef filter
}
YY_ACTION(void) yy_11_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_11_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_BITWISEOR);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_10_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_BITWISEAND);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_9_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_AND);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_OR);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_CAST);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_LESSTHAN);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_GREATERTHAN);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_EQUALS);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_LESSTHANOREQUAL);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_GREATERTHANOREQUAL);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_BinaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_BinaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_LIKE);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_UnaryOperator(yycontext *yy, char *yytext, int yyleng)
{
#define op1 yy->__val[-1]
#define filter yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_UnaryOperator\n"));
  {
  __ = filter; append_operand(&__->operand.op, op1);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef op1
#undef filter
}
YY_ACTION(void) yy_3_UnaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_UnaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_OFTYPE);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_UnaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_UnaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_ISNULL);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_UnaryFilter(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_UnaryFilter\n"));
  {
  __ = create_operator(&yy->global, UA_FILTEROPERATOR_NOT);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_WhereClause(yycontext *yy, char *yytext, int yyleng)
{
#define t yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_WhereClause\n"));
  {
  yy->top = t;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef t
}
YY_ACTION(void) yy_2_SelectClause(yycontext *yy, char *yytext, int yyleng)
{
#define sao2 yy->__val[-1]
#define sao yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_SelectClause\n"));
  {
  append_select(&yy->global, sao2);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef sao2
#undef sao
}
YY_ACTION(void) yy_1_SelectClause(yycontext *yy, char *yytext, int yyleng)
{
#define sao2 yy->__val[-1]
#define sao yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SelectClause\n"));
  {
  append_select(&yy->global, sao);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef sao2
#undef sao
}

YY_RULE(int) yy_Comment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Comment"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchChar(yy, '#')) goto l3;
  l4:;	
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;  if (!yy_Enter(yy)) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;
  }  if (!yymatchDot(yy)) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;
  }  if (!yy_Enter(yy)) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchString(yy, "/*")) goto l1;
  l7:;	
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;
  {  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;
  {  int yypos11= yy->__pos, yythunkpos11= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\204\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos11; yy->__thunkpos= yythunkpos11;
  }  if (!yymatchDot(yy)) goto l10;  goto l9;
  l10:;	  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;  if (!yymatchChar(yy, '/')) goto l8;
  }
  l9:;	  goto l7;
  l8:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;
  }  if (!yymatchString(yy, "*/")) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Enter(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Enter"));
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yymatchString(yy, "\r\n")) goto l14;  goto l13;
  l14:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yymatchChar(yy, '\n')) goto l15;  goto l13;
  l15:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;  if (!yymatchChar(yy, '\r')) goto l12;
  }
  l13:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Enter", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Enter", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Space(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "Space"));
  l17:;	
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;
  {  int yypos19= yy->__pos, yythunkpos19= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l20;  goto l19;
  l20:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yymatchChar(yy, '\t')) goto l21;  goto l19;
  l21:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;  if (!yy_Enter(yy)) goto l18;
  }
  l19:;	  goto l17;
  l18:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_JsonValue(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "JsonValue"));
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yy_JsonArray(yy)) goto l24;  goto l23;
  l24:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yy_QuotedString(yy)) goto l25;  goto l23;
  l25:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;
  l27:;	
  {  int yypos28= yy->__pos, yythunkpos28= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l28;  goto l27;
  l28:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;
  }  goto l23;
  l26:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yymatchString(yy, "true")) goto l29;  goto l23;
  l29:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yymatchString(yy, "false")) goto l30;  goto l23;
  l30:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yymatchString(yy, "null")) goto l22;
  }
  l23:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "JsonValue", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "JsonValue", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_JsonArray(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "JsonArray"));  if (!yymatchChar(yy, '[')) goto l31;  if (!yy__(yy)) goto l31;
  l32:;	
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;  if (!yy_JsonValue(yy)) goto l33;  if (!yy__(yy)) goto l33;  if (!yymatchChar(yy, ',')) goto l33;  if (!yy__(yy)) goto l33;  goto l32;
  l33:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;
  }  if (!yy_JsonValue(yy)) goto l31;  if (!yy__(yy)) goto l31;  if (!yymatchChar(yy, ']')) goto l31;
  yyprintf((stderr, "  ok   %s @ %s\n", "JsonArray", yy->__buf+yy->__pos));
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "JsonArray", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_JsonElement(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "JsonElement"));  if (!yy_QuotedString(yy)) goto l34;  if (!yy__(yy)) goto l34;  if (!yymatchChar(yy, ':')) goto l34;  if (!yy__(yy)) goto l34;  if (!yy_JsonValue(yy)) goto l34;
  yyprintf((stderr, "  ok   %s @ %s\n", "JsonElement", yy->__buf+yy->__pos));
  return 1;
  l34:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "JsonElement", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EscapedString(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EscapedString"));
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;  if (!yymatchChar(yy, '&')) goto l39;  if (!yymatchDot(yy)) goto l39;  goto l38;
  l39:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\076\000\000\113\323\000\124\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l40;  goto l35;
  l40:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;
  }  if (!yymatchDot(yy)) goto l35;
  }
  l38:;	
  l36:;	
  {  int yypos37= yy->__pos, yythunkpos37= yy->__thunkpos;
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;  if (!yymatchChar(yy, '&')) goto l42;  if (!yymatchDot(yy)) goto l42;  goto l41;
  l42:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\076\000\000\113\323\000\124\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l43;  goto l37;
  l43:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }  if (!yymatchDot(yy)) goto l37;
  }
  l41:;	  goto l36;
  l37:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EscapedString", yy->__buf+yy->__pos));
  return 1;
  l35:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EscapedString", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Ref(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Ref"));  if (!yymatchChar(yy, '$')) goto l44;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l44;
  l45:;	
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l46;  goto l45;
  l46:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Ref", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Ref", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_JsonObject(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "JsonObject"));  if (!yymatchChar(yy, '{')) goto l47;  if (!yy__(yy)) goto l47;
  l48:;	
  {  int yypos49= yy->__pos, yythunkpos49= yy->__thunkpos;  if (!yy_JsonElement(yy)) goto l49;  if (!yy__(yy)) goto l49;  if (!yymatchChar(yy, ',')) goto l49;  if (!yy__(yy)) goto l49;  goto l48;
  l49:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;
  }  if (!yy_JsonElement(yy)) goto l47;  if (!yy__(yy)) goto l47;  if (!yymatchChar(yy, '}')) goto l47;
  yyprintf((stderr, "  ok   %s @ %s\n", "JsonObject", yy->__buf+yy->__pos));
  return 1;
  l47:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "JsonObject", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_QualifiedName(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "QualifiedName"));
  {  int yypos51= yy->__pos, yythunkpos51= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l51;
  l53:;	
  {  int yypos54= yy->__pos, yythunkpos54= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l54;  goto l53;
  l54:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;
  }  if (!yymatchChar(yy, ':')) goto l51;  goto l52;
  l51:;	  yy->__pos= yypos51; yy->__thunkpos= yythunkpos51;
  }
  l52:;	  if (!yy_EscapedString(yy)) goto l50;
  yyprintf((stderr, "  ok   %s @ %s\n", "QualifiedName", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QualifiedName", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_QuotedString(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "QuotedString"));  if (!yymatchChar(yy, '"')) goto l55;
  l56:;	
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;
  {  int yypos58= yy->__pos, yythunkpos58= yy->__thunkpos;  if (!yymatchString(yy, "\\\"")) goto l59;  goto l58;
  l59:;	  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l60;  goto l57;
  l60:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;
  }  if (!yymatchDot(yy)) goto l57;
  }
  l58:;	  goto l56;
  l57:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;
  }  if (!yymatchChar(yy, '"')) goto l55;
  yyprintf((stderr, "  ok   %s @ %s\n", "QuotedString", yy->__buf+yy->__pos));
  return 1;
  l55:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QuotedString", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NumericRange(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NumericRange"));  if (!yymatchChar(yy, '[')) goto l61;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\020\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l61;
  l62:;	
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\020\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l63;  goto l62;
  l63:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;
  }  if (!yymatchChar(yy, ']')) goto l61;
  yyprintf((stderr, "  ok   %s @ %s\n", "NumericRange", yy->__buf+yy->__pos));
  return 1;
  l61:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NumericRange", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Attribute(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Attribute"));  if (!yymatchChar(yy, '#')) goto l64;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l64;
  l65:;	
  {  int yypos66= yy->__pos, yythunkpos66= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l66;  goto l65;
  l66:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Attribute", yy->__buf+yy->__pos));
  return 1;
  l64:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Attribute", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Path(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Path"));  if (!yymatchChar(yy, '/')) goto l67;  if (!yy_QualifiedName(yy)) goto l67;
  l68:;	
  {  int yypos69= yy->__pos, yythunkpos69= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l69;  if (!yy_QualifiedName(yy)) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos69; yy->__thunkpos= yythunkpos69;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Path", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Path", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NodeId(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NodeId"));
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yymatchString(yy, "ns=")) goto l71;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l71;
  l73:;	
  {  int yypos74= yy->__pos, yythunkpos74= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos74; yy->__thunkpos= yythunkpos74;
  }  if (!yymatchChar(yy, ';')) goto l71;  goto l72;
  l71:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;
  }
  l72:;	
  {  int yypos75= yy->__pos, yythunkpos75= yy->__thunkpos;  if (!yymatchString(yy, "i=")) goto l76;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l76;
  l77:;	
  {  int yypos78= yy->__pos, yythunkpos78= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l78;  goto l77;
  l78:;	  yy->__pos= yypos78; yy->__thunkpos= yythunkpos78;
  }  goto l75;
  l76:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;  if (!yymatchString(yy, "s=")) goto l79;  if (!yy_EscapedString(yy)) goto l79;  goto l75;
  l79:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;  if (!yymatchString(yy, "g=")) goto l80;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l80;
  l81:;	
  {  int yypos82= yy->__pos, yythunkpos82= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l82;  goto l81;
  l82:;	  yy->__pos= yypos82; yy->__thunkpos= yythunkpos82;
  }  goto l75;
  l80:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;  if (!yymatchString(yy, "b=")) goto l70;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\043\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l70;
  l83:;	
  {  int yypos84= yy->__pos, yythunkpos84= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\043\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l84;  goto l83;
  l84:;	  yy->__pos= yypos84; yy->__thunkpos= yythunkpos84;
  }
  }
  l75:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NodeId", yy->__buf+yy->__pos));
  return 1;
  l70:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NodeId", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BinaryFilter(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "BinaryFilter"));
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;
  {  int yypos88= yy->__pos, yythunkpos88= yy->__thunkpos;  if (!yymatchString(yy, "LIKE")) goto l89;  goto l88;
  l89:;	  yy->__pos= yypos88; yy->__thunkpos= yythunkpos88;  if (!yymatchString(yy, "<=>")) goto l87;
  }
  l88:;	  yyDo(yy, yy_1_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l87:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos91= yy->__pos, yythunkpos91= yy->__thunkpos;  if (!yymatchString(yy, "GREATEREQUAL")) goto l92;  goto l91;
  l92:;	  yy->__pos= yypos91; yy->__thunkpos= yythunkpos91;  if (!yymatchString(yy, ">=")) goto l90;
  }
  l91:;	  yyDo(yy, yy_2_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l90:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos94= yy->__pos, yythunkpos94= yy->__thunkpos;  if (!yymatchString(yy, "LESSEQUAL")) goto l95;  goto l94;
  l95:;	  yy->__pos= yypos94; yy->__thunkpos= yythunkpos94;  if (!yymatchString(yy, "<=")) goto l93;
  }
  l94:;	  yyDo(yy, yy_3_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l93:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yymatchString(yy, "EQUAL")) goto l98;  goto l97;
  l98:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;  if (!yymatchString(yy, "==")) goto l96;
  }
  l97:;	  yyDo(yy, yy_4_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l96:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yymatchString(yy, "GREATER")) goto l101;  goto l100;
  l101:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;  if (!yymatchChar(yy, '>')) goto l99;
  }
  l100:;	  yyDo(yy, yy_5_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l99:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos103= yy->__pos, yythunkpos103= yy->__thunkpos;  if (!yymatchString(yy, "LESS")) goto l104;  goto l103;
  l104:;	  yy->__pos= yypos103; yy->__thunkpos= yythunkpos103;  if (!yymatchChar(yy, '<')) goto l102;
  }
  l103:;	  yyDo(yy, yy_6_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l102:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yymatchString(yy, "CAST")) goto l107;  goto l106;
  l107:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;  if (!yymatchString(yy, "->")) goto l105;
  }
  l106:;	  yyDo(yy, yy_7_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l105:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos109= yy->__pos, yythunkpos109= yy->__thunkpos;  if (!yymatchString(yy, "OR")) goto l110;  goto l109;
  l110:;	  yy->__pos= yypos109; yy->__thunkpos= yythunkpos109;  if (!yymatchString(yy, "||")) goto l108;
  }
  l109:;	  yyDo(yy, yy_8_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l108:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos112= yy->__pos, yythunkpos112= yy->__thunkpos;  if (!yymatchString(yy, "AND")) goto l113;  goto l112;
  l113:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yymatchString(yy, "&&")) goto l111;
  }
  l112:;	  yyDo(yy, yy_9_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l111:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos115= yy->__pos, yythunkpos115= yy->__thunkpos;  if (!yymatchString(yy, "BITAND")) goto l116;  goto l115;
  l116:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;  if (!yymatchChar(yy, '&')) goto l114;
  }
  l115:;	  yyDo(yy, yy_10_BinaryFilter, yy->__begin, yy->__end);  goto l86;
  l114:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  {  int yypos117= yy->__pos, yythunkpos117= yy->__thunkpos;  if (!yymatchString(yy, "BITOR")) goto l118;  goto l117;
  l118:;	  yy->__pos= yypos117; yy->__thunkpos= yythunkpos117;  if (!yymatchChar(yy, '|')) goto l85;
  }
  l117:;	  yyDo(yy, yy_11_BinaryFilter, yy->__begin, yy->__end);
  }
  l86:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "BinaryFilter", yy->__buf+yy->__pos));
  return 1;
  l85:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BinaryFilter", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_UnaryFilter(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "UnaryFilter"));
  {  int yypos120= yy->__pos, yythunkpos120= yy->__thunkpos;
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yymatchString(yy, "NOT")) goto l123;  goto l122;
  l123:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;  if (!yymatchChar(yy, '!')) goto l121;
  }
  l122:;	  yyDo(yy, yy_1_UnaryFilter, yy->__begin, yy->__end);  goto l120;
  l121:;	  yy->__pos= yypos120; yy->__thunkpos= yythunkpos120;  if (!yymatchString(yy, "ISNULL")) goto l124;  yyDo(yy, yy_2_UnaryFilter, yy->__begin, yy->__end);  goto l120;
  l124:;	  yy->__pos= yypos120; yy->__thunkpos= yythunkpos120;  if (!yymatchString(yy, "OFTYPE")) goto l119;  yyDo(yy, yy_3_UnaryFilter, yy->__begin, yy->__end);
  }
  l120:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "UnaryFilter", yy->__buf+yy->__pos));
  return 1;
  l119:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "UnaryFilter", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_InListOperator(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "InListOperator"));  yyDo(yy, yy_1_InListOperator, yy->__begin, yy->__end);  if (!yymatchString(yy, "INLIST")) goto l125;  if (!yy__(yy)) goto l125;  if (!yy_Operand(yy)) goto l125;  yyDo(yy, yySet, -3, 0);  if (!yy__(yy)) goto l125;  if (!yymatchChar(yy, '[')) goto l125;  if (!yy__(yy)) goto l125;  yyDo(yy, yy_2_InListOperator, yy->__begin, yy->__end);
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_Operand(yy)) goto l126;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l126;  yyDo(yy, yy_3_InListOperator, yy->__begin, yy->__end);
  l128:;	
  {  int yypos129= yy->__pos, yythunkpos129= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l129;  if (!yy__(yy)) goto l129;  if (!yy_Operand(yy)) goto l129;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l129;  yyDo(yy, yy_4_InListOperator, yy->__begin, yy->__end);  goto l128;
  l129:;	  yy->__pos= yypos129; yy->__thunkpos= yythunkpos129;
  }  goto l127;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }
  l127:;	  if (!yy__(yy)) goto l125;  if (!yymatchChar(yy, ']')) goto l125;
  yyprintf((stderr, "  ok   %s @ %s\n", "InListOperator", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l125:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "InListOperator", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BetweenOperator(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "BetweenOperator"));  if (!yymatchString(yy, "BETWEEN")) goto l130;  if (!yy__(yy)) goto l130;  if (!yy_Operand(yy)) goto l130;  yyDo(yy, yySet, -3, 0);  if (!yy__(yy)) goto l130;  if (!yymatchChar(yy, '[')) goto l130;  if (!yy__(yy)) goto l130;  if (!yy_Operand(yy)) goto l130;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l130;  if (!yymatchChar(yy, ',')) goto l130;  if (!yy__(yy)) goto l130;  if (!yy_Operand(yy)) goto l130;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l130;  if (!yymatchChar(yy, ']')) goto l130;  yyDo(yy, yy_1_BetweenOperator, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "BetweenOperator", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BetweenOperator", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BinaryOperator(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "BinaryOperator"));  if (!yy_BinaryFilter(yy)) goto l131;  yyDo(yy, yySet, -3, 0);  if (!yy__(yy)) goto l131;  if (!yymatchChar(yy, '(')) goto l131;  if (!yy__(yy)) goto l131;  if (!yy_Operand(yy)) goto l131;  yyDo(yy, yySet, -2, 0);  if (!yymatchChar(yy, ',')) goto l131;  if (!yy__(yy)) goto l131;  if (!yy_Operand(yy)) goto l131;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l131;  if (!yymatchChar(yy, ')')) goto l131;  yyDo(yy, yy_1_BinaryOperator, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "BinaryOperator", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BinaryOperator", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_UnaryOperator(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "UnaryOperator"));  if (!yy_UnaryFilter(yy)) goto l132;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l132;  if (!yymatchChar(yy, '(')) goto l132;  if (!yy__(yy)) goto l132;  if (!yy_Operand(yy)) goto l132;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l132;  if (!yymatchChar(yy, ')')) goto l132;  yyDo(yy, yy_1_UnaryOperator, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "UnaryOperator", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "UnaryOperator", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SimpleAttributeOperand(yycontext *yy)
{
    int yypos0, yythunkpos0;
  yyprintf((stderr, "%s\n", "SimpleAttributeOperand"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l133;
#undef yytext
#undef yyleng
  }
  {  int yypos134= yy->__pos, yythunkpos134= yy->__thunkpos;  if (!yy_NodeId(yy)) goto l134;  goto l135;
  l134:;	  yy->__pos= yypos134; yy->__thunkpos= yythunkpos134;
  }
  l135:;	
  {  int yypos136= yy->__pos, yythunkpos136= yy->__thunkpos;  if (!yy_Path(yy)) goto l136;  goto l137;
  l136:;	  yy->__pos= yypos136; yy->__thunkpos= yythunkpos136;
  }
  l137:;	
  {  int yypos138= yy->__pos, yythunkpos138= yy->__thunkpos;  if (!yy_Attribute(yy)) goto l138;  goto l139;
  l138:;	  yy->__pos= yypos138; yy->__thunkpos= yythunkpos138;
  }
  l139:;	
  {  int yypos140= yy->__pos, yythunkpos140= yy->__thunkpos;  if (!yy_NumericRange(yy)) goto l140;  goto l141;
  l140:;	  yy->__pos= yypos140; yy->__thunkpos= yythunkpos140;
  }
  l141:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l133;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_SimpleAttributeOperand, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "SimpleAttributeOperand", yy->__buf+yy->__pos));
  return 1;
  l133:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SimpleAttributeOperand", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Literal(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Literal"));
  {  int yypos143= yy->__pos, yythunkpos143= yy->__thunkpos;  if (!yymatchString(yy, "INT32")) goto l144;  if (!yy__(yy)) goto l144;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l144;
#undef yytext
#undef yyleng
  }
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l145;  goto l146;
  l145:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;
  }
  l146:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l144;
  l147:;	
  {  int yypos148= yy->__pos, yythunkpos148= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l148;  goto l147;
  l148:;	  yy->__pos= yypos148; yy->__thunkpos= yythunkpos148;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l144;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Literal, yy->__begin, yy->__end);  goto l143;
  l144:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "STRING")) goto l149;  if (!yy__(yy)) goto l149;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l149;
#undef yytext
#undef yyleng
  }  if (!yy_QuotedString(yy)) goto l149;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l149;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_Literal, yy->__begin, yy->__end);  goto l143;
  l149:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "BOOL")) goto l150;  if (!yy__(yy)) goto l150;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l150;
#undef yytext
#undef yyleng
  }
  {  int yypos151= yy->__pos, yythunkpos151= yy->__thunkpos;  if (!yymatchString(yy, "true")) goto l152;  goto l151;
  l152:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;  if (!yymatchString(yy, "True")) goto l153;  goto l151;
  l153:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;  if (!yymatchString(yy, "false")) goto l154;  goto l151;
  l154:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;  if (!yymatchString(yy, "False")) goto l155;  goto l151;
  l155:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l150;
  }
  l151:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l150;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_Literal, yy->__begin, yy->__end);  goto l143;
  l150:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "INT16")) goto l156;  if (!yy__(yy)) goto l156;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l156;
#undef yytext
#undef yyleng
  }
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l157;  goto l158;
  l157:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;
  }
  l158:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l156;
  l159:;	
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l160;  goto l159;
  l160:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l156;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_4_Literal, yy->__begin, yy->__end);  goto l143;
  l156:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "INT64")) goto l161;  if (!yy__(yy)) goto l161;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l161;
#undef yytext
#undef yyleng
  }
  {  int yypos162= yy->__pos, yythunkpos162= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l162;  goto l163;
  l162:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;
  }
  l163:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l161;
  l164:;	
  {  int yypos165= yy->__pos, yythunkpos165= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l165;  goto l164;
  l165:;	  yy->__pos= yypos165; yy->__thunkpos= yythunkpos165;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l161;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_5_Literal, yy->__begin, yy->__end);  goto l143;
  l161:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "UINT16")) goto l166;  if (!yy__(yy)) goto l166;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l166;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l166;
  l167:;	
  {  int yypos168= yy->__pos, yythunkpos168= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l168;  goto l167;
  l168:;	  yy->__pos= yypos168; yy->__thunkpos= yythunkpos168;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l166;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_6_Literal, yy->__begin, yy->__end);  goto l143;
  l166:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "UINT32")) goto l169;  if (!yy__(yy)) goto l169;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l169;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l169;
  l170:;	
  {  int yypos171= yy->__pos, yythunkpos171= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l171;  goto l170;
  l171:;	  yy->__pos= yypos171; yy->__thunkpos= yythunkpos171;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l169;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_7_Literal, yy->__begin, yy->__end);  goto l143;
  l169:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "UINT64")) goto l172;  if (!yy__(yy)) goto l172;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l172;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l172;
  l173:;	
  {  int yypos174= yy->__pos, yythunkpos174= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l174;  goto l173;
  l174:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l172;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_8_Literal, yy->__begin, yy->__end);  goto l143;
  l172:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "DOUBLE")) goto l175;  if (!yy__(yy)) goto l175;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l175;
#undef yytext
#undef yyleng
  }
  {  int yypos176= yy->__pos, yythunkpos176= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l176;  goto l177;
  l176:;	  yy->__pos= yypos176; yy->__thunkpos= yythunkpos176;
  }
  l177:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l175;
  l178:;	
  {  int yypos179= yy->__pos, yythunkpos179= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l179;  goto l178;
  l179:;	  yy->__pos= yypos179; yy->__thunkpos= yythunkpos179;
  }
  {  int yypos180= yy->__pos, yythunkpos180= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l180;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l180;
  l182:;	
  {  int yypos183= yy->__pos, yythunkpos183= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l183;  goto l182;
  l183:;	  yy->__pos= yypos183; yy->__thunkpos= yythunkpos183;
  }  goto l181;
  l180:;	  yy->__pos= yypos180; yy->__thunkpos= yythunkpos180;
  }
  l181:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l175;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_9_Literal, yy->__begin, yy->__end);  goto l143;
  l175:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "FLOAT")) goto l184;  if (!yy__(yy)) goto l184;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l184;
#undef yytext
#undef yyleng
  }
  {  int yypos185= yy->__pos, yythunkpos185= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l185;  goto l186;
  l185:;	  yy->__pos= yypos185; yy->__thunkpos= yythunkpos185;
  }
  l186:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l184;
  l187:;	
  {  int yypos188= yy->__pos, yythunkpos188= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l188;  goto l187;
  l188:;	  yy->__pos= yypos188; yy->__thunkpos= yythunkpos188;
  }
  {  int yypos189= yy->__pos, yythunkpos189= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l189;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l189;
  l191:;	
  {  int yypos192= yy->__pos, yythunkpos192= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l192;  goto l191;
  l192:;	  yy->__pos= yypos192; yy->__thunkpos= yythunkpos192;
  }  goto l190;
  l189:;	  yy->__pos= yypos189; yy->__thunkpos= yythunkpos189;
  }
  l190:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l184;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_10_Literal, yy->__begin, yy->__end);  goto l143;
  l184:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "NODEID")) goto l193;  if (!yy__(yy)) goto l193;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l193;
#undef yytext
#undef yyleng
  }  if (!yy_NodeId(yy)) goto l193;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l193;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_11_Literal, yy->__begin, yy->__end);  goto l143;
  l193:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "SBYTE")) goto l194;  if (!yy__(yy)) goto l194;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l194;
#undef yytext
#undef yyleng
  }
  {  int yypos195= yy->__pos, yythunkpos195= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l195;  goto l196;
  l195:;	  yy->__pos= yypos195; yy->__thunkpos= yythunkpos195;
  }
  l196:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l194;
  l197:;	
  {  int yypos198= yy->__pos, yythunkpos198= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l198;  goto l197;
  l198:;	  yy->__pos= yypos198; yy->__thunkpos= yythunkpos198;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l194;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_12_Literal, yy->__begin, yy->__end);  goto l143;
  l194:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "BYTE")) goto l199;  if (!yy__(yy)) goto l199;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l199;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l199;
  l200:;	
  {  int yypos201= yy->__pos, yythunkpos201= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l201;  goto l200;
  l201:;	  yy->__pos= yypos201; yy->__thunkpos= yythunkpos201;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l199;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_13_Literal, yy->__begin, yy->__end);  goto l143;
  l199:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "TIME")) goto l202;  if (!yy__(yy)) goto l202;  if (!yymatchChar(yy, '"')) goto l202;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l202;
#undef yytext
#undef yyleng
  }
  {  int yypos205= yy->__pos, yythunkpos205= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l206;  goto l205;
  l206:;	  yy->__pos= yypos205; yy->__thunkpos= yythunkpos205;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l207;  goto l205;
  l207:;	  yy->__pos= yypos205; yy->__thunkpos= yythunkpos205;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l208;  goto l205;
  l208:;	  yy->__pos= yypos205; yy->__thunkpos= yythunkpos205;  if (!yymatchChar(yy, '.')) goto l209;  goto l205;
  l209:;	  yy->__pos= yypos205; yy->__thunkpos= yythunkpos205;  if (!yymatchChar(yy, ':')) goto l202;
  }
  l205:;	
  l203:;	
  {  int yypos204= yy->__pos, yythunkpos204= yy->__thunkpos;
  {  int yypos210= yy->__pos, yythunkpos210= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l211;  goto l210;
  l211:;	  yy->__pos= yypos210; yy->__thunkpos= yythunkpos210;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l212;  goto l210;
  l212:;	  yy->__pos= yypos210; yy->__thunkpos= yythunkpos210;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l213;  goto l210;
  l213:;	  yy->__pos= yypos210; yy->__thunkpos= yythunkpos210;  if (!yymatchChar(yy, '.')) goto l214;  goto l210;
  l214:;	  yy->__pos= yypos210; yy->__thunkpos= yythunkpos210;  if (!yymatchChar(yy, ':')) goto l204;
  }
  l210:;	  goto l203;
  l204:;	  yy->__pos= yypos204; yy->__thunkpos= yythunkpos204;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l202;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l202;  yyDo(yy, yy_14_Literal, yy->__begin, yy->__end);  goto l143;
  l202:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "GUID")) goto l215;  if (!yy__(yy)) goto l215;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l215;
#undef yytext
#undef yyleng
  }
  {  int yypos218= yy->__pos, yythunkpos218= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l219;  goto l218;
  l219:;	  yy->__pos= yypos218; yy->__thunkpos= yythunkpos218;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l220;  goto l218;
  l220:;	  yy->__pos= yypos218; yy->__thunkpos= yythunkpos218;  if (!yymatchChar(yy, '-')) goto l215;
  }
  l218:;	
  l216:;	
  {  int yypos217= yy->__pos, yythunkpos217= yy->__thunkpos;
  {  int yypos221= yy->__pos, yythunkpos221= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l222;  goto l221;
  l222:;	  yy->__pos= yypos221; yy->__thunkpos= yythunkpos221;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l223;  goto l221;
  l223:;	  yy->__pos= yypos221; yy->__thunkpos= yythunkpos221;  if (!yymatchChar(yy, '-')) goto l217;
  }
  l221:;	  goto l216;
  l217:;	  yy->__pos= yypos217; yy->__thunkpos= yythunkpos217;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l215;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_15_Literal, yy->__begin, yy->__end);  goto l143;
  l215:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "BSTRING")) goto l224;  if (!yy__(yy)) goto l224;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l224;
#undef yytext
#undef yyleng
  }  if (!yy_QuotedString(yy)) goto l224;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l224;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_16_Literal, yy->__begin, yy->__end);  goto l143;
  l224:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "STATUSCODE")) goto l225;  if (!yy__(yy)) goto l225;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l225;
#undef yytext
#undef yyleng
  }
  {  int yypos228= yy->__pos, yythunkpos228= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l229;  goto l228;
  l229:;	  yy->__pos= yypos228; yy->__thunkpos= yythunkpos228;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l225;
  }
  l228:;	
  l226:;	
  {  int yypos227= yy->__pos, yythunkpos227= yy->__thunkpos;
  {  int yypos230= yy->__pos, yythunkpos230= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l231;  goto l230;
  l231:;	  yy->__pos= yypos230; yy->__thunkpos= yythunkpos230;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l227;
  }
  l230:;	  goto l226;
  l227:;	  yy->__pos= yypos227; yy->__thunkpos= yythunkpos227;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l225;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_17_Literal, yy->__begin, yy->__end);  goto l143;
  l225:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "EXPNODEID")) goto l232;  if (!yy__(yy)) goto l232;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l232;
#undef yytext
#undef yyleng
  }  if (!yy_QuotedString(yy)) goto l232;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l232;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_18_Literal, yy->__begin, yy->__end);  goto l143;
  l232:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "QNAME")) goto l233;  if (!yy__(yy)) goto l233;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l233;
#undef yytext
#undef yyleng
  }  if (!yy_QualifiedName(yy)) goto l233;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l233;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_19_Literal, yy->__begin, yy->__end);  goto l143;
  l233:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  if (!yymatchString(yy, "LOCALIZED")) goto l234;  if (!yy__(yy)) goto l234;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l234;
#undef yytext
#undef yyleng
  }  if (!yy_QuotedString(yy)) goto l234;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l234;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_20_Literal, yy->__begin, yy->__end);  goto l143;
  l234:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l235;
#undef yytext
#undef yyleng
  }  if (!yy_JsonObject(yy)) goto l235;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l235;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_21_Literal, yy->__begin, yy->__end);  goto l143;
  l235:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l236;
#undef yytext
#undef yyleng
  }  if (!yy_QuotedString(yy)) goto l236;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l236;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_22_Literal, yy->__begin, yy->__end);  goto l143;
  l236:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l237;
#undef yytext
#undef yyleng
  }
  {  int yypos238= yy->__pos, yythunkpos238= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l238;  goto l239;
  l238:;	  yy->__pos= yypos238; yy->__thunkpos= yythunkpos238;
  }
  l239:;	  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l237;
  l240:;	
  {  int yypos241= yy->__pos, yythunkpos241= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l241;  goto l240;
  l241:;	  yy->__pos= yypos241; yy->__thunkpos= yythunkpos241;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l237;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_23_Literal, yy->__begin, yy->__end);  goto l143;
  l237:;	  yy->__pos= yypos143; yy->__thunkpos= yythunkpos143;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l142;
#undef yytext
#undef yyleng
  }
  {  int yypos242= yy->__pos, yythunkpos242= yy->__thunkpos;  if (!yymatchString(yy, "true")) goto l243;  goto l242;
  l243:;	  yy->__pos= yypos242; yy->__thunkpos= yythunkpos242;  if (!yymatchString(yy, "True")) goto l244;  goto l242;
  l244:;	  yy->__pos= yypos242; yy->__thunkpos= yythunkpos242;  if (!yymatchString(yy, "false")) goto l245;  goto l242;
  l245:;	  yy->__pos= yypos242; yy->__thunkpos= yythunkpos242;  if (!yymatchString(yy, "False")) goto l142;
  }
  l242:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l142;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_24_Literal, yy->__begin, yy->__end);
  }
  l143:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Literal", yy->__buf+yy->__pos));
  return 1;
  l142:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Literal", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RefAssignment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "RefAssignment"));  if (!yy_RefOperand(yy)) goto l246;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l246;  if (!yymatchString(yy, ":=")) goto l246;  if (!yy__(yy)) goto l246;  if (!yy_Operand(yy)) goto l246;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_RefAssignment, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "RefAssignment", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l246:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RefAssignment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RefOperand(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RefOperand"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l247;
#undef yytext
#undef yyleng
  }  if (!yy_Ref(yy)) goto l247;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l247;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_RefOperand, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "RefOperand", yy->__buf+yy->__pos));
  return 1;
  l247:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RefOperand", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Operator(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Operator"));
  {  int yypos249= yy->__pos, yythunkpos249= yy->__thunkpos;  if (!yy_UnaryOperator(yy)) goto l250;  goto l249;
  l250:;	  yy->__pos= yypos249; yy->__thunkpos= yythunkpos249;  if (!yy_BinaryOperator(yy)) goto l251;  goto l249;
  l251:;	  yy->__pos= yypos249; yy->__thunkpos= yythunkpos249;  if (!yy_BetweenOperator(yy)) goto l252;  goto l249;
  l252:;	  yy->__pos= yypos249; yy->__thunkpos= yythunkpos249;  if (!yy_InListOperator(yy)) goto l248;
  }
  l249:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Operator", yy->__buf+yy->__pos));
  return 1;
  l248:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Operator", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Operand(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Operand"));
  {  int yypos254= yy->__pos, yythunkpos254= yy->__thunkpos;  if (!yymatchChar(yy, '(')) goto l255;  if (!yy__(yy)) goto l255;  if (!yy_Operand(yy)) goto l255;  if (!yy__(yy)) goto l255;  if (!yymatchChar(yy, ')')) goto l255;  goto l254;
  l255:;	  yy->__pos= yypos254; yy->__thunkpos= yythunkpos254;  if (!yy_RefOperand(yy)) goto l256;  goto l254;
  l256:;	  yy->__pos= yypos254; yy->__thunkpos= yythunkpos254;  if (!yy_Literal(yy)) goto l257;  goto l254;
  l257:;	  yy->__pos= yypos254; yy->__thunkpos= yythunkpos254;  if (!yy_Operator(yy)) goto l258;  goto l254;
  l258:;	  yy->__pos= yypos254; yy->__thunkpos= yythunkpos254;  if (!yy_SimpleAttributeOperand(yy)) goto l253;
  }
  l254:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Operand", yy->__buf+yy->__pos));
  return 1;
  l253:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Operand", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ForClause(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ForClause"));  if (!yymatchString(yy, "FOR")) goto l259;  if (!yy__(yy)) goto l259;  if (!yy_RefAssignment(yy)) goto l259;  if (!yy__(yy)) goto l259;
  l260:;	
  {  int yypos261= yy->__pos, yythunkpos261= yy->__thunkpos;  if (!yymatchString(yy, "AND")) goto l261;  if (!yy__(yy)) goto l261;  if (!yy_RefAssignment(yy)) goto l261;  if (!yy__(yy)) goto l261;  goto l260;
  l261:;	  yy->__pos= yypos261; yy->__thunkpos= yythunkpos261;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ForClause", yy->__buf+yy->__pos));
  return 1;
  l259:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ForClause", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_WhereClause(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "WhereClause"));  if (!yymatchString(yy, "WHERE")) goto l262;  if (!yy__(yy)) goto l262;
  {  int yypos263= yy->__pos, yythunkpos263= yy->__thunkpos;  if (!yy_Operator(yy)) goto l264;  yyDo(yy, yySet, -1, 0);  goto l263;
  l264:;	  yy->__pos= yypos263; yy->__thunkpos= yythunkpos263;  if (!yy_RefOperand(yy)) goto l262;  yyDo(yy, yySet, -1, 0);
  }
  l263:;	  yyDo(yy, yy_1_WhereClause, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "WhereClause", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l262:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WhereClause", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SelectClause(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "SelectClause"));  if (!yymatchString(yy, "SELECT")) goto l265;  if (!yy__(yy)) goto l265;  if (!yy_Operand(yy)) goto l265;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l265;  yyDo(yy, yy_1_SelectClause, yy->__begin, yy->__end);
  l266:;	
  {  int yypos267= yy->__pos, yythunkpos267= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l267;  if (!yy__(yy)) goto l267;  if (!yy_Operand(yy)) goto l267;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l267;  yyDo(yy, yy_2_SelectClause, yy->__begin, yy->__end);  goto l266;
  l267:;	  yy->__pos= yypos267; yy->__thunkpos= yythunkpos267;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "SelectClause", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l265:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SelectClause", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "_"));
  {  int yypos269= yy->__pos, yythunkpos269= yy->__thunkpos;  if (!yy_Space(yy)) goto l270;  goto l269;
  l270:;	  yy->__pos= yypos269; yy->__thunkpos= yythunkpos269;  if (!yy_Comment(yy)) goto l268;
  }
  l269:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
  l268:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EventFilter(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EventFilter"));  if (!yy__(yy)) goto l271;  if (!yy_SelectClause(yy)) goto l271;  if (!yy__(yy)) goto l271;
  {  int yypos272= yy->__pos, yythunkpos272= yy->__thunkpos;  if (!yy_WhereClause(yy)) goto l272;  if (!yy__(yy)) goto l272;  goto l273;
  l272:;	  yy->__pos= yypos272; yy->__thunkpos= yythunkpos272;
  }
  l273:;	
  {  int yypos274= yy->__pos, yythunkpos274= yy->__thunkpos;  if (!yy_ForClause(yy)) goto l274;  if (!yy__(yy)) goto l274;  goto l275;
  l274:;	  yy->__pos= yypos274; yy->__thunkpos= yythunkpos274;
  }
  l275:;	
  {  int yypos276= yy->__pos, yythunkpos276= yy->__thunkpos;  if (!yymatchDot(yy)) goto l276;  goto l271;
  l276:;	  yy->__pos= yypos276; yy->__thunkpos= yythunkpos276;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EventFilter", yy->__buf+yy->__pos));
  return 1;
  l271:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EventFilter", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(static int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(static int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_EventFilter);
}

YY_PARSE(static yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif


UA_StatusCode
UA_EventFilter_parse(UA_EventFilter *filter, UA_ByteString *content) {
    yycontext ctx;
    memset(&ctx, 0, sizeof(yycontext));
    TAILQ_INIT(&ctx.global.select_list);
    ctx.input = *content;
    int res = yyparse(&ctx);
    if(res == 0)
        ctx.status = UA_STATUSCODE_BADINTERNALERROR;
    if(ctx.status != UA_STATUSCODE_GOOD) {
        yyrelease(&ctx);
        OperandList_clear(&ctx.global);
        return ctx.status;
    }

    UA_EventFilter_init(filter);
    ctx.status = create_filter(&ctx.global, filter, ctx.top);
    yyrelease(&ctx);
    OperandList_clear(&ctx.global);
    if(ctx.status != UA_STATUSCODE_GOOD)
        UA_EventFilter_clear(filter);
    return ctx.status;
}
