#ifndef CERTIFICATE_EKU_H_
#define CERTIFICATE_EKU_H_

#include <open62541/types.h>

/* Regression certificates supplied with the CertificateInvalidWrongEKU report.
 * Only the public certificates are needed for the profile checks. */

static UA_Byte RSA_CLIENT_WRONG_EKU_PEM[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIEvTCCAqWgAwIBAgIURnINnNj4tPdhZv/87cesxNZw8nUwDQYJKoZIhvcNAQEL\n"
    "BQAwPzELMAkGA1UEBhMCREUxFjAUBgNVBAoMDVRlc3QgT3JnIE5hbWUxGDAWBgNV\n"
    "BAMMD3Jvb3RfY2EuZGVmYXVsdDAeFw0yNjA2MTEwNTI0MTFaFw0yNjA3MTIwNTI0\n"
    "MTFaMEAxCzAJBgNVBAYTAkRFMRYwFAYDVQQKDA1UZXN0IE9yZyBOYW1lMRkwFwYD\n"
    "VQQDDBBjbGllbnQud3JvbmdfZWt1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\n"
    "CgKCAQEAsNhhQOTIcSEPO+4p9BzYAGjhEdDENYEMtOmZUXoSfxsc+OfFiO8onoSw\n"
    "L1vUTZPKHUai2hSH5+DReJt+1ITxCSbXWb3nBhNg6M8UwBjGh2L4LOm82U78WkU9\n"
    "5FF3sWjilv5cYyt5krmCe0C+fCrwDiGyFr+7/USAPFTtha1v4o/j4zb6+DvfSbaT\n"
    "V4dm4Qp38KCvA+QyuAbP4hUvwJOCjphRlcuzlQzNwb/yPKugXXwVSkwVIYI2rBvQ\n"
    "e5Lro1Y8VHmj6WeB/hSpDMTVhJVlunVsFY8Gcn38ag8KPyQ9tgCyfa13kwlMJEP1\n"
    "7Et/OiBz3IXktXr8gNA/4A3UpJ5udQIDAQABo4GvMIGsMAwGA1UdEwEB/wQCMAAw\n"
    "DgYDVR0PAQH/BAQDAgTwMB0GA1UdDgQWBBT8md4ZHW0PvRRlbv8ZP32V+f0yczAf\n"
    "BgNVHSMEGDAWgBTOQCezXymEK245VO/j9TOQybgaRTA3BgNVHREEMDAugglsb2Nh\n"
    "bGhvc3SGG3Vybjp0ZXN0LmNsaWVudC5hcHBsaWNhdGlvbocEfwAAATATBgNVHSUE\n"
    "DDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAgEASc1pJpRXbKm4LyoIbOzc\n"
    "n53uVAxos0LAFMPow3GsGRrYRS9BBgts4b3iYS7VoW/BautnerqlvfPJ1piESLxV\n"
    "9FQmzwLRicqdxSz5y8VqWCl1kQDGbfsyYg72/+c1dgxuy9SLzBsFF0zRakqTeW+L\n"
    "S5pvX4cYA6SPTJUnU7GysFg9WOkLuWU6Ya3NA4dpuSO8frXpcfzMEQdSCx1MsRLA\n"
    "Q4fbyk7rDAB3xU/JzsfJd6V14BuKHMjTTxZ94xnZXfX10CTu/ccnOJOToanTzOnX\n"
    "OrvAu+CPss1hzMOUemrqxUdPPxKgYFx1QbSGFqj7bN3pNJi5JpgcxsK0buk1qnVF\n"
    "3tykCw1BhliEgZmgwhaOtGe/FnhN1VO7JmWfoVFR0LT6yDi6ejhbE5HoEuaqsxq8\n"
    "J/NASMrHKU5xx018ONG/8I1pMwxpo0Ip6btKaplEn6ksbn5r8Tearp6S07g1zmnU\n"
    "2KdRdstcfi1IrzYUO0V3eA8CdVp7PtEUbeI/sam4nks1VqdHcoX0xHMm0C1/Jnyl\n"
    "B7Gcf0r8CwiFo6nYfHFJIKc+FA7m/vJz+hOC7PaHC3hHyA3wqMd+LeUpqV5IM9aq\n"
    "hGURef+tb5NxtgRhnlHSvrAOSK+PAZkA42OsRaksgEtYiBV73x8pQ8dMWxxKX00T\n"
    "zn4zqsO3+23F+wsJyhgNGww=\n"
    "-----END CERTIFICATE-----\n";

static UA_Byte RSA_SERVER_WRONG_EKU_PEM[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIEvTCCAqWgAwIBAgIUbCXTgycnnytMEoUMcrII+QGgGVYwDQYJKoZIhvcNAQEL\n"
    "BQAwPzELMAkGA1UEBhMCREUxFjAUBgNVBAoMDVRlc3QgT3JnIE5hbWUxGDAWBgNV\n"
    "BAMMD3Jvb3RfY2EuZGVmYXVsdDAeFw0yNjA2MTEwNTI0MTFaFw0yNjA3MTIwNTI0\n"
    "MTFaMEAxCzAJBgNVBAYTAkRFMRYwFAYDVQQKDA1UZXN0IE9yZyBOYW1lMRkwFwYD\n"
    "VQQDDBBzZXJ2ZXIud3JvbmdfZWt1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\n"
    "CgKCAQEA3oPeH2rQbZDhYPbl8QDlleJRkNwB/dOvFeECSFOPxiUFHckaja9cqTdR\n"
    "o3YXLyXBuhfyOzTgPE1tIkiYn7fRjXAy2xcG64G29s2vqdsL1eCailV9V8E40x0/\n"
    "+wdBa0p5qX9e6x5yxdCne/hrYD5EjXTHvuUEGBcS2FzbjG+PekMxsSxm4MQKGNjn\n"
    "bDSxTqV9/lW2znVltzNgaEB4l2pXrcTVYVBRmu+syLAQ70e94jut0Q38UjI+gT/r\n"
    "Hoc7rjdFJN0/CfWAA89Exb6WNXDSi28zSwpaVAxmqaFaRhjRJTnz/oLFIqsHeZVU\n"
    "3ZdS6oexWO+8qPA6nJsR+GlscR7FlQIDAQABo4GvMIGsMAwGA1UdEwEB/wQCMAAw\n"
    "DgYDVR0PAQH/BAQDAgTwMB0GA1UdDgQWBBTiBeTVFwzZmS1NuqXv9GazTSttBzAf\n"
    "BgNVHSMEGDAWgBTOQCezXymEK245VO/j9TOQybgaRTA3BgNVHREEMDAugglsb2Nh\n"
    "bGhvc3SGG3Vybjp0ZXN0LnNlcnZlci5hcHBsaWNhdGlvbocEfwAAATATBgNVHSUE\n"
    "DDAKBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAgEAricMDYtfKSOQNXybsRh+\n"
    "nYXw4Mp+wgPGwzVfXwcmqmEB6G7jaUiGh8+Qpb3zUJGMVk2dOj00v97DDzSMgQh7\n"
    "HbcdE5FykIGsR2D1+z5hbNcABZ1AC5h0a+KrY9oIfH3Rk+5fXgaU4EO0qvG52KoU\n"
    "tBUAIM/fJ40WPeRpxq67iQHegyFLRxbx/tzuw/Z/flRcKEwJsgz1E3GIY4X87xGl\n"
    "RWFTYbAQu8SGVc5L8YuMbA/EGvy+6nXnfMASMrijE0aKFuq4h8D8kEk+dBTvlHX4\n"
    "ZcRcpqOo+Bp5UVWKN5iiFlWT28j1ZH+9RmYlR+49AQeiFZV+zg83bHb1GK1R5/ib\n"
    "qHRAjq3hM7o9tWSygrJ6w5H7SpYIXm3LhH9FnpX7ORYS6BG65ewjnBj0VBif7FuM\n"
    "BAzVnEHiP1i5XXkSTHygCrcSkwOeTLLIUOFyBSUfGectKQJ5/46HWMMBep7qxXGe\n"
    "JLguZi6PPqwkv0FH0hUHFCjJ8ltc4y3Dfhmgg5RmBd69vpiicDJgD7Lycpsclc0f\n"
    "Rj+clnvkjyzFt5jSCkq8inZzgZIVHyFEZ49jMTPcB1mAw502YUGsPdUo8g2f0pf3\n"
    "z8WaBygYb1Z4SV71rKFWDoJDgxcXtOkCBxN7nNfuiLKy6+bSHHPaQ6Ap5y3yVhXk\n"
    "7PJHN5gx1kRY4ANn0qZDOjY=\n"
    "-----END CERTIFICATE-----\n";

static UA_Byte ECC_SERVER_MISSING_EKU_PEM[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICHTCCAcSgAwIBAgIUE+E1YmrTU3ISrSVC/cdKj7FOZUEwCgYIKoZIzj0EAwIw\n"
    "PzELMAkGA1UEBhMCREUxFjAUBgNVBAoMDVRlc3QgT3JnIE5hbWUxGDAWBgNVBAMM\n"
    "D3Jvb3RfY2EuZGVmYXVsdDAeFw0yNjA2MTEwNTI0MTNaFw0yNjA3MTIwNTI0MTNa\n"
    "MEIxCzAJBgNVBAYTAkRFMRYwFAYDVQQKDA1UZXN0IE9yZyBOYW1lMRswGQYDVQQD\n"
    "DBJzZXJ2ZXIubWlzc2luZ19la3UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARu\n"
    "nMTfZYVv463IOVnUqg0/GgILXwt301lE42KPtdJeqRtkelHUDbOJUZ+mgrdiB70h\n"
    "GUkn3/k9evpDe1nUTLQYo4GaMIGXMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQD\n"
    "AgWgMB0GA1UdDgQWBBR+RM51frpAvERtnzGsZkmHRzX5CjAfBgNVHSMEGDAWgBSM\n"
    "Q7Shn/3JX9JCZbLGBTCiU1iGCTA3BgNVHREEMDAugglsb2NhbGhvc3SGG3Vybjp0\n"
    "ZXN0LnNlcnZlci5hcHBsaWNhdGlvbocEfwAAATAKBggqhkjOPQQDAgNHADBEAiBy\n"
    "3cfN35qF1pQcbyGAKECZ+QKxQbtawYBk7OuJCT5cQgIgQX496DzvcYKQHomBOHA2\n"
    "TJpaWJ0w4vVb+uIbP7DA0bY=\n"
    "-----END CERTIFICATE-----\n";

#define RSA_CLIENT_WRONG_EKU_LENGTH (sizeof(RSA_CLIENT_WRONG_EKU_PEM) - 1)
#define RSA_SERVER_WRONG_EKU_LENGTH (sizeof(RSA_SERVER_WRONG_EKU_PEM) - 1)
#define ECC_SERVER_MISSING_EKU_LENGTH (sizeof(ECC_SERVER_MISSING_EKU_PEM) - 1)

#endif /* CERTIFICATE_EKU_H_ */
