version: 2.1

jobs:
  unit-tests-encryption-mbedtls:
    machine:
      image: ubuntu-2204:current
    environment:
      ETHERNET_INTERFACE: docker0
    steps:
      - checkout

      - run:
          name: Install base dependencies
          command: |
            sudo apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
              build-essential cmake libcap2-bin pkg-config libssl-dev \
              python3-sphinx graphviz check libxml2-dev libpcap-dev

      - run:
          name: Install MBedTLS dependencies
          command: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
              libmbedtls-dev

      - run:
          name: Run unit_tests_encryption MBEDTLS
          command: |
            mkdir -p build; cd build; rm -rf *
            cmake -DCMAKE_BUILD_TYPE=Debug \
                  -DUA_BUILD_EXAMPLES=ON \
                  -DUA_BUILD_UNIT_TESTS=ON \
                  -DUA_ENABLE_ENCRYPTION=MBEDTLS \
                  -DUA_FORCE_WERROR=ON \
                  -DUA_NAMESPACE_ZERO=FULL \
                  ..
            make
            for filename in bin/tests/*; do
                sudo setcap cap_sys_ptrace,cap_net_raw,cap_net_admin=eip $filename
            done
            ctest --output-on-failure

workflows:
  version: 2
  build-and-test:
    jobs:
      - unit-tests-encryption-mbedtls
