/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_pubsub_PubSubMain */

#ifndef _Included_jni_pubsub_PubSubMain
#define _Included_jni_pubsub_PubSubMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_pubsub_PubSubMain
 * Method:    getMessage
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_jni_pubsub_PubSubMain_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
