/* Generated by re2c 1.1.1 */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 *
 *    Copyright 2020 (c) Fraunhofer IOSB (Author: Julius Pfrommer)
 *
 */

#include <open62541/types.h>
#include <open62541/types_generated_handling.h>
#include <open62541/util.h>
#include "base64.h"

/* Lexing and parsing of builtin data types. These are helper functions that not
 * required by the SDK internally. But they are useful for users who want to use
 * standard-specified humand readable encodings for NodeIds, etc.
 *
 * This compilation unit uses the re2c lexer generator. The final C source is
 * generated with the following script:
 *
 *   re2c -i --no-generation-date  ua_types_lex.re > ua_types_lex.c
 *
 * In order that users of the SDK don't need to install re2c, always commit a
 * recent ua_types_lex.c if changes are made to the lexer. */

const char *yyt1;const char *yyt2;const char *yyt3;const char *yyt4;


/* The generated lexer defines global variables. Protect with a mutex. */
#if UA_MULTITHREADING >= 100
UA_LOCK_TYPE(parserMutex)
#endif

static UA_StatusCode
parse_guid(UA_Guid *guid, const UA_Byte *s, const UA_Byte *e) {
    size_t len = (size_t)(e - s);
    if(len != 36 || s[8] != '-' || s[13] != '-' || s[23] != '-')
        return UA_STATUSCODE_BADINTERNALERROR;

    UA_UInt32 tmp;
    if(UA_readNumberWithBase(s, 8, &tmp, 16) != 8)
        return UA_STATUSCODE_BADINTERNALERROR;
    guid->data1 = tmp;

    if(UA_readNumberWithBase(&s[9], 4, &tmp, 16) != 4)
        return UA_STATUSCODE_BADINTERNALERROR;
    guid->data2 = (UA_UInt16)tmp;

    if(UA_readNumberWithBase(&s[14], 4, &tmp, 16) != 4)
        return UA_STATUSCODE_BADINTERNALERROR;
    guid->data3 = (UA_UInt16)tmp;

    if(UA_readNumberWithBase(&s[19], 4, &tmp, 16) != 4)
        return UA_STATUSCODE_BADINTERNALERROR;
    guid->data4[0] = (UA_Byte)tmp;
    guid->data4[1] = (UA_Byte)(tmp >> 8);

    if(UA_readNumberWithBase(&s[24], 8, &tmp, 16) != 8)
        return UA_STATUSCODE_BADINTERNALERROR;
    guid->data4[2] = (UA_Byte)tmp;
    guid->data4[3] = (UA_Byte)(tmp >> 8);
    guid->data4[4] = (UA_Byte)(tmp >> 16);
    guid->data4[5] = (UA_Byte)(tmp >> 24);

    if(UA_readNumberWithBase(&s[32], 4, &tmp, 16) != 4)
        return UA_STATUSCODE_BADINTERNALERROR;
    guid->data4[6] = (UA_Byte)tmp;
    guid->data4[7] = (UA_Byte)(tmp >> 8);

    return UA_STATUSCODE_GOOD;
}

UA_StatusCode
UA_Guid_parse(UA_Guid *guid, const UA_String str) {
    UA_StatusCode res = parse_guid(guid, str.data, str.data + str.length);
    if(res != UA_STATUSCODE_GOOD)
        *guid = UA_GUID_NULL;
    return res;
}

static UA_StatusCode
parse_nodeid_body(UA_NodeId *id, const char *body, const char *end) {
    size_t len = (size_t)(end - (body+2));
    UA_StatusCode res = UA_STATUSCODE_GOOD;
    switch(*body) {
    case 'i': {
        if(UA_readNumber((const UA_Byte*)body+2, len, &id->identifier.numeric) != len)
            return UA_STATUSCODE_BADINTERNALERROR;
        id->identifierType = UA_NODEIDTYPE_NUMERIC;
        break;
    }
    case 's': {
        UA_String tmpstr;
        tmpstr.data = (UA_Byte*)(uintptr_t)body+2;
        tmpstr.length = len;
        res = UA_String_copy(&tmpstr, &id->identifier.string);
        if(res != UA_STATUSCODE_GOOD)
            break;
        id->identifierType = UA_NODEIDTYPE_STRING;
        break;
    }
    case 'g':
        res = parse_guid(&id->identifier.guid, (const UA_Byte*)body+2, (const UA_Byte*)end);
        if(res == UA_STATUSCODE_GOOD)
            id->identifierType = UA_NODEIDTYPE_GUID;
        break;
    case 'b':
        id->identifier.byteString.data =
            UA_unbase64((const unsigned char*)body+2, len,
                        &id->identifier.byteString.length);
        if(!id->identifier.byteString.data && len > 0)
            return UA_STATUSCODE_BADINTERNALERROR;
        id->identifierType = UA_NODEIDTYPE_BYTESTRING;
        break;
    default:
        return UA_STATUSCODE_BADINTERNALERROR;
    }
    return res;
}

static UA_StatusCode
parse_nodeid(UA_NodeId *id, const char *input, const char *end) {
    *id = UA_NODEID_NULL; /* Reset the NodeId */
    const char *pos = input, *ns = NULL, *nse= NULL;
    
{
	char yych;
	if ((end - input) < 4) goto error;
	yych = *input;
	switch (yych) {
	case 'b':
	case 'g':
	case 'i':
	case 's':
		yyt1 = yyt2 = NULL;
		goto yy4;
	case 'n':	goto yy5;
	default:	goto yy2;
	}
yy2:
	++input;
yy3:
	{ error: return UA_STATUSCODE_BADINTERNALERROR; }
yy4:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy6;
	default:	goto yy3;
	}
yy5:
	yych = *(pos = ++input);
	switch (yych) {
	case 's':	goto yy8;
	default:	goto yy3;
	}
yy6:
	++input;
	ns = yyt1;
	nse = yyt2;
	{
        if(ns) {
            UA_UInt32 tmp;
            size_t len = (size_t)(nse - ns);
            if(UA_readNumber((const UA_Byte*)ns, len, &tmp) != len)
                return UA_STATUSCODE_BADINTERNALERROR;
            id->namespaceIndex = (UA_UInt16)tmp;
        }

        /* From the current position until the end of the input */
        return parse_nodeid_body(id, &input[-2], end);
    }
yy8:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy10;
	default:	goto yy9;
	}
yy9:
	input = pos;
	goto yy3;
yy10:
	yych = *++input;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = input;
		goto yy11;
	default:	goto yy9;
	}
yy11:
	++input;
	if ((end - input) < 3) goto error;
	yych = *input;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	case ';':
		yyt2 = input;
		goto yy13;
	default:	goto yy9;
	}
yy13:
	yych = *++input;
	switch (yych) {
	case 'b':
	case 'g':
	case 'i':
	case 's':	goto yy14;
	default:	goto yy9;
	}
yy14:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy6;
	default:	goto yy9;
	}
}

}

UA_StatusCode
UA_NodeId_parse(UA_NodeId *id, const UA_String str) {
    UA_LOCK(parserMutex);
    UA_StatusCode res =
        parse_nodeid(id, (const char*)str.data, (const char*)str.data+str.length);
    if(res != UA_STATUSCODE_GOOD)
        UA_NodeId_clear(id);
    UA_UNLOCK(parserMutex);
    return res;
}

static UA_StatusCode
parse_expandednodeid(UA_ExpandedNodeId *id, const char *input, const char *end) {
    *id = UA_EXPANDEDNODEID_NULL; /* Reset the NodeId */
    const char *pos = input, *svr = NULL, *svre = NULL, *nsu = NULL, *ns = NULL, *body = NULL;
    
{
	char yych;
	if ((end - input) < 7) goto error;
	yych = *input;
	switch (yych) {
	case 'b':
	case 'g':
	case 'i':
		yyt1 = yyt2 = yyt3 = yyt4 = NULL;
		goto yy19;
	case 'n':
		yyt1 = yyt2 = NULL;
		goto yy20;
	case 's':
		yyt1 = yyt2 = yyt3 = yyt4 = NULL;
		goto yy21;
	default:	goto yy17;
	}
yy17:
	++input;
yy18:
	{ error: return UA_STATUSCODE_BADINTERNALERROR; }
yy19:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy22;
	default:	goto yy18;
	}
yy20:
	yych = *(pos = ++input);
	switch (yych) {
	case 's':	goto yy24;
	default:	goto yy18;
	}
yy21:
	yych = *(pos = ++input);
	switch (yych) {
	case '=':	goto yy22;
	case 'v':	goto yy26;
	default:	goto yy18;
	}
yy22:
	++input;
	svr = yyt1;
	svre = yyt2;
	ns = yyt3;
	nsu = yyt4;
	body = input - 2;
	{
        if(svr) {
            size_t len = (size_t)((svre) - svr);
            if(UA_readNumber((const UA_Byte*)svr, len, &id->serverIndex) != len)
                return UA_STATUSCODE_BADINTERNALERROR;
        }

        if(nsu) {
            size_t len = (size_t)((body-1) - nsu);
            UA_String nsuri;
            nsuri.data = (UA_Byte*)(uintptr_t)nsu;
            nsuri.length = len;
            UA_StatusCode res = UA_String_copy(&nsuri, &id->namespaceUri);
            if(res != UA_STATUSCODE_GOOD)
                return res;
        } else if(ns) {
            UA_UInt32 tmp;
            size_t len = (size_t)((body-1) - ns);
            if(UA_readNumber((const UA_Byte*)ns, len, &tmp) != len)
                return UA_STATUSCODE_BADINTERNALERROR;
            id->nodeId.namespaceIndex = (UA_UInt16)tmp;
        }

        /* From the current position until the end of the input */
        return parse_nodeid_body(&id->nodeId, &input[-2], end);
    }
yy24:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy27;
	case 'u':	goto yy28;
	default:	goto yy25;
	}
yy25:
	input = pos;
	goto yy18;
yy26:
	yych = *++input;
	switch (yych) {
	case 'r':	goto yy29;
	default:	goto yy25;
	}
yy27:
	yych = *++input;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = input;
		goto yy30;
	default:	goto yy25;
	}
yy28:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy32;
	default:	goto yy25;
	}
yy29:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy33;
	default:	goto yy25;
	}
yy30:
	++input;
	if ((end - input) < 3) goto error;
	yych = *input;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case ';':	goto yy34;
	default:	goto yy25;
	}
yy32:
	yych = *++input;
	switch (yych) {
	case '\n':	goto yy25;
	case ';':
		yyt4 = input;
		goto yy37;
	default:
		yyt4 = input;
		goto yy35;
	}
yy33:
	yych = *++input;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = input;
		goto yy38;
	default:	goto yy25;
	}
yy34:
	yych = *++input;
	switch (yych) {
	case 'b':
	case 'g':
	case 'i':
	case 's':
		yyt4 = NULL;
		goto yy40;
	default:	goto yy25;
	}
yy35:
	++input;
	if ((end - input) < 3) goto error;
	yych = *input;
	switch (yych) {
	case '\n':	goto yy25;
	case ';':	goto yy37;
	default:	goto yy35;
	}
yy37:
	yych = *++input;
	switch (yych) {
	case 'b':
	case 'g':
	case 'i':
	case 's':
		yyt3 = NULL;
		goto yy40;
	default:	goto yy25;
	}
yy38:
	++input;
	if ((end - input) < 8) goto error;
	yych = *input;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy38;
	case ';':
		yyt2 = input;
		goto yy41;
	default:	goto yy25;
	}
yy40:
	yych = *++input;
	switch (yych) {
	case '=':	goto yy22;
	default:	goto yy25;
	}
yy41:
	yych = *++input;
	switch (yych) {
	case 'b':
	case 'g':
	case 'i':
	case 's':
		yyt3 = yyt4 = NULL;
		goto yy40;
	case 'n':	goto yy42;
	default:	goto yy25;
	}
yy42:
	yych = *++input;
	switch (yych) {
	case 's':	goto yy24;
	default:	goto yy25;
	}
}

}

UA_StatusCode
UA_ExpandedNodeId_parse(UA_ExpandedNodeId *id, const UA_String str) {
    UA_LOCK(parserMutex);
    UA_StatusCode res =
        parse_expandednodeid(id, (const char*)str.data, (const char*)str.data+str.length);
    if(res != UA_STATUSCODE_GOOD)
        UA_ExpandedNodeId_clear(id);
    UA_UNLOCK(parserMutex);
    return res;
}
