name: Zephyr Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build open62541 for Zephyr
        run: |
            sudo apt update
            sudo apt -y install python3 python3-pip git cmake build-essential \
                ninja-build gperf ccache dfu-util device-tree-compiler wget \
                python3-dev python3-setuptools python3-tk python3-wheel xz-utils file \
                make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1 curl
            python3 -m pip install west
            wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.17.0/zephyr-sdk-0.17.0_linux-x86_64.tar.xz 
            tar xf zephyr-sdk-0.17.0_linux-x86_64.tar.xz
            ./zephyr-sdk-0.17.0/setup.sh -t all -h -c
            cd examples/zephyr
            west init -l server
            west update
            python3 -m pip install -r zephyr/scripts/requirements.txt
            cd server
            west build -p -b native_sim
