#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

cyclictest_max_latency - Plugin to get the max latency of the cyclictest application

=head1 CONFIGURATION

This is a wildcard plugin. To get the max latency that occurred due to a culprit for the victim, link
cyclictest_max_latency to this file. E.g.

  ln -s /usr/share/munin/plugins/cyclictest_max_latency \
        /etc/munin/plugins/cyclictest_max_latency

...will get the max latency of the cyclictest.

=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

CORES="0 1 2 3"
if [ "$1" = "config" ]; then
        # The title of the graph
        echo "graph_title Cyclictest maximum latency"
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        #echo 'graph_args --base 0'
        # The Y-axis label
        echo 'graph_vlabel Latency (us)'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 microseconds instead of
        # 420 millimicroseconds)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category system'
        echo 'graph_printf %3.0lf'
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the
        # individual fields.
        echo "graph_info The maximum latency in us represents the worst-case latency obtained when running the Cyclictest application (High resolution test program) "
        echo 'latencycore0.label Max latency in core 0'
        echo 'latencycore0.info Maximum latency in core 0 in us (microseconds)'
        echo 'latencycore1.label Max latency in core 1'
        echo 'latencycore1.info Maximum latency in core 1 in us (microseconds)'
        echo 'latencycore2.label Max latency in core 2'
        echo 'latencycore2.info Maximum latency in core 2 in us (microseconds)'
        echo 'latencycore3.label Max latency in core 3'
        echo 'latencycore3.info Maximum latency in core 3 in us (microseconds)'

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

if [ -s /usr/local/src/cyclictest.log ]; then
        latencycore0=`tail -5 /usr/local/src/cyclictest.log | head -1 | tr -s " " | awk '{ print $NF }'`
        latencycore1=`tail -4 /usr/local/src/cyclictest.log | head -1 | tr -s " " | awk '{ print $NF }'`
        latencycore2=`tail -3 /usr/local/src/cyclictest.log | head -1 | tr -s " " | awk '{ print $NF }'`
        latencycore3=`tail -2 /usr/local/src/cyclictest.log | head -1 | tr -s " " | awk '{ print $NF }'`

        echo "latencycore0.value ${latencycore0#0}"
        echo "latencycore1.value ${latencycore1#0}"
        echo "latencycore2.value ${latencycore2#0}"
        echo "latencycore3.value ${latencycore3#0}"
fi
