#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

ethtool_rx_queue_1_statistics_ - Plugin to monitor received packets, packet drops of the first queue of network interfaces

=head1 CONFIGURATION

This is a wildcard plugin. To monitor an interface, link
ethtool_rx_queue_1_statistics_<interface> to this file. E.g.

  ln -s /usr/share/munin/plugins/ethtool_rx_queue_1_statistics_ \
        /etc/munin/plugins/ethtool_rx_queue_1_statistics_eth0

...will monitor eth0.

=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

INTERFACE=${0##*/ethtool_rx_queue_1_statistics_}

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        #Warnings and critical messages can be created using below commands. For now, it has been commented.

        # The title of the graph
        echo "graph_title RX statistics of PubSub application in $INTERFACE"
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        #echo 'graph_args --base 0'
        # The Y-axis label
        echo 'graph_vlabel Packet throughput'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 microseconds instead of
        # 420 millimicroseconds)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category network'
        echo 'graph_printf %3.0lf'
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the
        # individual fields.
        echo 'graph_info PubSub application received and dropped packets in receive queue 1 for every 5 minutes interval'

        echo "receivedPackets_queue.label Received packets in rx queue 1"
        echo "receivedPackets_queue.info Packets received in rx queue 1"
        echo 'receivedPackets_queue.type DERIVE'
        echo 'receivedPackets_queue.min 0'

        echo "droppedPackets_queue.label Dropped packets in rx queue 1" ;
        echo "droppedPackets_queue.info Packets dropped in rx queue 1" ;
        echo 'droppedPackets_queue.type DERIVE'
        echo 'droppedPackets_queue.min 0'

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

if [ -s /usr/local/src/ethtool_receive_statistics_$INTERFACE.txt ]; then
    received_packet_queue=`cat /usr/local/src/ethtool_receive_statistics_$INTERFACE.txt | tr -s " " | cut -d" " -f2`
    dropped_packet_queue=`cat /usr/local/src/ethtool_receive_statistics_$INTERFACE.txt | tr -s " " | cut -d" " -f4`
fi
echo "receivedPackets_queue.value $received_packet_queue"
echo "droppedPackets_queue.value $dropped_packet_queue"

