#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

network_bandwidth_utilisation_ - Plugin to monitor the network bandwidth utilisation of various network interfaces

=head1 CONFIGURATION

This is a wildcard plugin. To monitor an interface, link
network_bandwidth_utilisation_<interface> to this file. E.g.

  ln -s /usr/share/munin/plugins/network_bandwidth_utilisation_ \
        /etc/munin/plugins/network_bandwidth_utilisation_eth0

...will monitor eth0.

=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

INTERFACE=${0##*/network_bandwidth_utilisation_}

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        # The title of the graph
        echo "graph_title Network bandwidth utilisation in $INTERFACE"
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        #echo 'graph_args --base 0'
        # The Y-axis label
        echo 'graph_vlabel Bandwidth'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 microseconds instead of
        # 420 millimicroseconds)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category network'
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the
        # individual fields.

        echo 'incoming_packet_bandwidth.label Incoming Network Bandwidth in KB/s'
        echo 'incoming_packet_bandwidth.info Network bandwidth of the Incoming Packetes in KB/s'

        echo 'outing_packet_bandwidth.label Outgoing Network Bandwidth in KB/s'
        echo 'outing_packet_bandwidth.info Network bandwidth of the Outgoing Packets in KB/s'

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

if [ -s /usr/local/src/network_bandwidth_utilisation_$INTERFACE.txt ]; then
        statisticsFile=/usr/local/src/network_bandwidth_utilisation_$INTERFACE.txt
        incoming_packet_bandwidth=`cat $statisticsFile | tr -s " " | cut -d" " -f1`
        outgoing_packet_bandwidth=`cat $statisticsFile | tr -s " " | cut -d" " -f2`

        echo "incoming_packet_bandwidth.value $incoming_packet_bandwidth"
        echo "outgoing_packet_bandwidth.value $outgoing_packet_bandwidth"
fi