#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

load - Plugin to monitor the jitter of phc2sys time synchronization

=head1 CONFIGURATION

=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look.

if [ "$1" = "config" ]; then

        # The host name this plugin is for. (Can be overridden to have
        # one machine answer for several)

        # The title of the graph
        echo 'graph_title PHC2SYS jitter'
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        echo 'graph_args --base 1000'
        # The Y-axis label
        echo 'graph_vlabel Jitter (ns)'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 load instead of
        # 420 milliload)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category network'
        echo 'graph_printf %3.0lf'
        # The fields. "label" is used in the legend. "label" is the only
        # required subfield.
        echo 'min.label min'
        echo 'max.label max'
        # These two read the environment for warning values for the field
        # "load".  If "load_warning" or "warning" aren't set in the
        # environment, no warning levels are set.  Likewise for "load_critical"
        # and "critical".
        print_warning min
        print_critical min
        print_warning max
        print_critical max
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the field
        # "load".
        echo 'graph_info The jitter describes the quality of the time synchronization between the network chip and the systems.'
        echo 'min.info 5 minute minimum jitter'
        echo 'max.info 5 minute maximum jitter'

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.
max=-999999999
min=999999999

for i in `tail -300 /var/log/phc2sys.log | tr -s " " | cut -d" " -f5`
do
  if test $i -lt $min 2>/dev/null
  then
    min=$i
  elif test $i -gt $max 2>/dev/null
  then
    max=$i
  fi
done
if test $max = -999999999 -o $min = 999999999
then
  echo "min.value U"
  echo "max.value U"
else
  echo "min.value $min"
  echo "max.value $max"
fi
