#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

subscriberThreadJitterStatistics - Plugin to monitor subscriber start time jitter

=head1 CONFIGURATION

This is a wildcard plugin. To monitor subscriber start time jitter, link
subscriberThreadJitterStatistics file in /etc/munin/plugins/ folder to this file. E.g.

  ln -s /usr/share/munin/plugins/subscriberThreadJitterStatistics \
        /etc/munin/plugins/subscriberThreadJitterStatistics



=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        #Warnings and critical messages can be created using below commands. For now, it has been commented.

        # The title of the graph
        echo "graph_title Subscriber thread start time jitter - Publisher side"
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        #echo 'graph_args --base 0'
        # The Y-axis label
        echo 'graph_vlabel Jitter (ns)'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 microseconds instead of
        # 420 millimicroseconds)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category network'
        echo 'graph_printf %3.0lf'
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the
        # individual fields.
        echo 'graph_info This graph shows jitter of subscriber thread'


        echo "subscriber_jitter.label Subscriber thread start time jitter" ;
        echo "subscriber_jitter.info Subscriber thread start time jitter"

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

if [ -s /usr/local/src/open62541_pubsub_maxlatency.txt ]; then
        #Obtain the maximum latency from the open62541_pubsub_maxlatency.txt file and convert it using cdef function and plot the jitter of the maximum latencies
        jitter=`cat /usr/local/src/open62541_pubsub_maxlatency.txt |  tr -s " " | cut -d" " -f7`
        echo "subscriber_jitter.value $jitter"
fi
