#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

subscriberThreadDataProcessingStatistics - Plugin to monitor time taken by subscriber to process received data

=head1 CONFIGURATION

This is a wildcard plugin. To monitor subscriber data processing time, link
subscriberThreadDataProcessingStatistics file in /etc/munin/plugins/ folder to this file. E.g.

  ln -s /usr/share/munin/plugins/subscriberThreadDataProcessingStatistics \
        /etc/munin/plugins/subscriberThreadDataProcessingStatistics

=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        # The title of the graph
        echo "graph_title Subscriber Data Processing Time"
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        #echo 'graph_args --base 0'
        # The Y-axis label
        echo 'graph_vlabel Processing Time (ns)'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 microseconds instead of
        # 420 millimicroseconds)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category network'
        echo 'graph_printf %3.0lf'
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the
        # individual fields.
        echo 'graph_info This graph shows time taken by subscriber thread to process received data'

        echo "subscriber_processingtime.label Subscriber thread processing time" ;
        echo "subscriber_processingtime.info Subscriber thread processing time"

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

if test -e /usr/local/src/open62541_pubsub_maxlatency.txt
then
    #Obtain the maximum latency from the text file and convert it using cdef function and plot the time taken by the subscriber thread to process data
    procesingTime=`cat  /usr/local/src/open62541_pubsub_maxlatency.txt |  tr -s " " | cut -d" " -f10`
elif test -e /usr/local/src/open62541_pubsub_maxlatency_loopback.txt
then
    procesingTime=`cat  /usr/local/src/open62541_pubsub_maxlatency_loopback.txt |  tr -s " " | cut -d" " -f7`
fi
echo "subscriber_processingtime.value $procesingTime"

