#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

tc_qdisc_statistics_ - Plugin to monitor packets sent, packet drops, and
overlimits of network interfaces

=head1 CONFIGURATION

This is a wildcard plugin. To monitor an interface, link
tc_qdisc_statistics_<interface> to this file. E.g.

  ln -s /usr/share/munin/plugins/tc_qdisc_statistics_ \
        /etc/munin/plugins/tc_qdisc_statistics_eth0

...will monitor eth0.

=head1 NOTES

If run with the "autoconf"-parameter, give our opinion on whether we
should be run on this system or not. This is optional, and only used
by munin-config. In the case of this plugin, we should most probably
always be included.

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

INTERFACE=${0##*/tc_qdisc_statistics_}

# If run with the "autoconf"-parameter, give our opinion on wether we
# should be run on this system or not. This is optinal, and only used by
# munin-config. In the case of this plugin, we should most probably
# always be included.
if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        # The title of the graph
        echo "graph_title TX statistics of etf queue in $INTERFACE"
        # Arguments to "rrdtool graph". In this case, tell it that the
        # lower limit of the graph is '0', and that 1k=1000 (not 1024)
        #echo 'graph_args --base 0'
        # The Y-axis label
        echo 'graph_vlabel Packet throughput'
        # We want Cur/Min/Avg/Max unscaled (i.e. 0.42 microseconds instead of
        # 420 millimicroseconds)
        echo 'graph_scale no'
        # Graph category. Defaults to 'other'
        echo 'graph_category network'
        echo 'graph_printf %3.0lf'
        # This one is purely to add an explanation to the web page. The first
        # one is for the graph itself, while the second one is for the
        # individual fields.
        echo 'graph_info Sent packets and dropped packets in the etf queue'

        echo 'sentPackets.label Sent packets'
        echo 'sentPackets.info Packets sent in the etf queue'
        echo 'sentPackets.type DERIVE'
        echo 'sentPackets.min 0'

        echo 'droppedPackets.label Dropped packets'
        echo 'droppedPackets.info Packets dropped in the etf queue'
        echo 'droppedPackets.type DERIVE'
        echo 'droppedPackets.min 0'

        echo 'overlimits.label Overlimits'
        echo 'overlimits.info Overlimits in the etf queue'
        echo 'overlimits.type DERIVE'
        echo 'overlimits.min 0'
        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

statisticsFile=/usr/local/src/tc_statistics_$INTERFACE.txt
sent_packet=`cat $statisticsFile | tr -s " " | cut -d" " -f1`
dropped_packet=`cat $statisticsFile | tr -s " " | cut -d" " -f2`
overlimits=`cat $statisticsFile | tr -s " " | cut -d" " -f3`

echo "sentPackets.value $sent_packet"
echo "droppedPackets.value $dropped_packet"
echo "overlimits.value $overlimits"
